#!/bin/bash
inFile="$(realpath "$1")"
outFile="$(realpath "$2")"
size="$3"

tmpDir=/tmp/AppImage-thumnailer
if ! mkdir -p $tmpDir; then
  echo "Cannot create temprary directory to work in!"
  echo "Quitting..."
  exit 1
fi
cd $tmpDir

thumb="$("$inFile" --appimage-extract '.DirIcon')"
while [ "$(file -bi "$thumb")" = 'inode/symlink' ]; do
  thumb="$(file "$thumb" | rev | cut -d " " -f 1 | rev)"
  thumb="$("$inFile" --appimage-extract "$thumb")"
done
convert  -background none -resize "$size" "$thumb" "$outFile"
rm -r $tmpDir
